### ISSUE TITLE
Training for accuracy vs. efficiency

### ISSUE THREAD

**Issue by beperron** [wjbmattingly/youtube_text_classification#1]
Excellent tutorial on text classification!  I was able to reproduce your example on text classification.  However, when I change from efficiency to accuracy, the classification score remains at .49 and doesn't improve over any of the epochs.  I understand that this configuration uses `en_core_web_lg` as opposed to the smaller model `en_core_web_sm`.   If I wanted to use the large model (for accuracy), is there a different procedure that should be used?  My interest is to generalize this classification task to a different problem, but I am wanting to optimize on accuracy (rather than efficiency).  Any advice you can offer would be great.

**Comment by alessiodam** [comment]
spaCy has a config.cfg generator like he used in his video, just use that generator and select accuracy

**Comment by alessiodam** [comment]
Did you get it fixed?
